










-- h2 : jdbc:h2:tcp://localhost/~/test

create table member
(
    id bigint generated by default as identity,
-- null 값이면 db가 자동으로 id 값을 채워줌
-- generated by default as identity
    name varchar(255),
    primary key(id)
)

insert into member (name) values ('spring1')

select * from member